export default function DefaultStyle() {    
    return {
    "backgroundColor": "transparent",
    "width": "auto",
    "height": "auto",
    "color": "inherit",
    "fontSize": "medium",
    "fontWeight": "normal",
    "lineHeight": "normal",
    "padding": "0",
    "margin": "0",
    "border": "none",
    "borderRadius": "0",
    "boxShadow": "none",
    "textAlign": "start",
    "display": "inline",
    "flex": "0 1 auto",
    "justifyContent": "normal",
    "alignItems": "normal",
    "overflow": "visible",
    "position": "static",
    "zIndex": "auto",
    "opacity": "1",
    "visibility": "visible",
    "cursor": "auto",
    "transition": "none",
    "transform": "none",
    "clipPath": "none",
    "content": "normal",
    "float": "none",
    "clear": "none",
    "whiteSpace": "normal",
    "letterSpacing": "normal",
    "wordSpacing": "normal",
    "textDecoration": "none",
    "backgroundImage": "none",
    "backgroundSize": "auto",
    "backgroundPosition": "0% 0%",
    "backgroundRepeat": "repeat",
    "boxSizing": "content-box",
    "maxWidth": "none",
    "minWidth": "0",
    "maxHeight": "none",
    "minHeight": "0",
    "outline": "none",
    "clip": "auto",
    "perspective": "none",
    "visibility": "visible",
    "animation": "none",
    "direction": "ltr",
    "unicodeBidi": "normal",
    "overflowX": "visible",
    "overflowY": "visible",
    "resize": "none",
    "scrollBehavior": "auto",
    "listStyle": "disc outside none",
    "userSelect": "auto",
    "pointerEvents": "auto",
    "tableLayout": "auto",
    "emptyCells": "show",
    "verticalAlign": "baseline"
  }
}